# Generated by Django 3.1.2 on 2021-01-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('class_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfomationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id_array', models.CharField(max_length=100)),
                ('class_model', models.ManyToManyField(to='visuals.ClassModel')),
                ('teacher_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visuals.teacherinfomationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=50)),
                ('document_url', models.CharField(max_length=2000)),
                ('teacher_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visuals.teacherinfomationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visuals.classmodel')),
                ('student_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visuals.studentinformationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=50)),
                ('document_url', models.CharField(max_length=2000)),
                ('student_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visuals.studentinformationmodel')),
            ],
        ),
        migrations.AddField(
            model_name='classmodel',
            name='subject_model',
            field=models.ManyToManyField(to='visuals.SubjectModel'),
        ),
    ]
